dist: xenial
language: node_js
addons:
  apt:
    sources:
      - sourceline: ppa:ethereum/ethereum
    packages:
    - ethereum
# test on stable and LTS
node_js:
#  - "node" #stable
  - "lts/*"
  
before_install:
  - geth --datadir chain1010 init genesis.json
  - npm install arc-web3
branches:
 only:
   - master
script: node start.js
#after_script:
#   - npm run travis:after
